separate default value changes into 3 categories: added, removed, changed
oasdiff/oasdiff pull request #356
Opened 2023-08-03 15:10 UTC by tibulca

2023-08-03 15:42 UTC, blva approved these changes

2023-08-07 10:23 UTC, reuvenharrison commented on checker/check-request-property-default-value-changed.go
add this checker to defaultChecks

2023-08-07 10:41 UTC, reuvenharrison requested changes
Please address the inline comment and then we can merge

2023-08-07 21:08 UTC, tibulca commented on checker/check-request-property-default-value-changed.go
done, thank you

2023-08-08 05:09 UTC, merged